# Generated by Django 5.0 on 2023-12-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
